@usersp = http://localhost:3000/user/usersp
@login = http://localhost:3000/user/login
@getmaterias = http://localhost:3000/user/getMaterias


POST {{login}}
Content-Type: application/json

{
    "dni" : "10",
    "password" : "1234"
}

###
POST {{usersp}}
Content-Type: application/json

{
    "dni" : "10",
    "nombre" : "juan",
    "password" : "1234"
}

###
GET {{getmaterias}}
auth : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkbmkiOiIxMCIsImlhdCI6MTcxODgwNjU1MCwiZXhwIjoxNzE5MDIyNTUwfQ.NqoP_S2ptLeC8paMs2F8JLoNFzbNrKZ5xYpdAGk_VwY